### ISSUE TITLE
Progress so far with Landscapes test installation

### ISSUE THREAD

**Issue by zombyte** [OpenWhere/landscapes.io#63]
1. Instruction for MongoDB installation not included.
2. Instruction for NodeJS installation not included.
3. Instruction for NPM installation not included. 
4. 'npm install' by itself resulted in 'npm start' producing the errors seen below.

>     [ec2-user@ip-10-104-224-97 landscapes.io]$ npm start
> 
>     > landscapes.io@0.1.0 start /home/ec2-user/landscapes.io
>     > NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback
> 
>     sh: concurrently: command not found
> 
>     npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
>     npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
>     npm ERR! node v6.10.2
>     npm ERR! npm  v3.10.10
>     npm ERR! file sh
>     npm ERR! code ELIFECYCLE
>     npm ERR! errno ENOENT
>     npm ERR! syscall spawn
>     npm ERR! landscapes.io@0.1.0 start: `NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback`
>     npm ERR! spawn ENOENT
>     npm ERR! 
>     npm ERR! Failed at the landscapes.io@0.1.0 start script 'NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback'.
>     npm ERR! Make sure you have the latest version of node.js and npm installed.
>     npm ERR! If you do, this is most likely a problem with the landscapes.io package,
>     npm ERR! not with npm itself.
>     npm ERR! Tell the author that this fails on your system:
>     npm ERR!     NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback
>     npm ERR! You can get information on how to open an issue for this project with:
>     npm ERR!     npm bugs landscapes.io
>     npm ERR! Or if that isn't available, you can get their info via:
>     npm ERR!     npm owner ls landscapes.io
>     npm ERR! There is likely additional logging output above.
> 
>     npm ERR! Please include the following file with any support request:
>     npm ERR!     /home/ec2-user/landscapes.io/npm-debug.log

5. After manually installing a few of the npm packages (concurrently, nodemon, & webpack), we realized that the start may need packages specified in the dev packages list so attempted 'npm install --only=dev'. I think it ran properly, but I'm no developer. Afterwards 'npm start' produced the errors seen below.

>     [ec2-user@ip-10-104-224-97 landscapes.io]$ npm start
> 
>     > landscapes.io@0.1.0 start /home/ec2-user/landscapes.io
>     > NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback
> 
>     [1] module.js:471
>     [1]     throw err;
>     [1]     ^
>     [1] 
>     [1] Error: Cannot find module 'winston'
>     [1]     at Function.Module._resolveFilename (module.js:469:15)
>     [1]     at Function.Module._load (module.js:417:25)
>     [1]     at Module.require (module.js:497:17)
>     [1]     at require (internal/module.js:20:19)
>     [1]     at Object.<anonymous> (/home/ec2-user/landscapes.io/server.hot.reload.js:3:17)
>     [1]     at Module._compile (module.js:570:32)
>     [1]     at Object.Module._extensions..js (module.js:579:10)
>     [1]     at Module.load (module.js:487:32)
>     [1]     at tryModuleLoad (module.js:446:12)
>     [1]     at Function.Module._load (module.js:438:3)
>     [1] node server.hot.reload exited with code 1
>     --> Sending SIGTERM to other processes..
>     [0] nodemon ./server/init.js --exec babel-node exited with code 0
> 
>     npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
>     npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
>     npm ERR! node v6.10.2
>     npm ERR! npm  v3.10.10
>     npm ERR! code ELIFECYCLE
>     npm ERR! landscapes.io@0.1.0 start: `NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback`
>     npm ERR! Exit status 1
>     npm ERR! 
>     npm ERR! Failed at the landscapes.io@0.1.0 start script 'NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback'.
>     npm ERR! Make sure you have the latest version of node.js and npm installed.
>     npm ERR! If you do, this is most likely a problem with the landscapes.io package,
>     npm ERR! not with npm itself.
>     npm ERR! Tell the author that this fails on your system:
>     npm ERR!     NODE_ENV=development PROTOCOL=http PUBLIC_IP=0.0.0.0 PORT=8080 concurrently --kill-others "nodemon ./server/init.js --exec babel-node" "node server.hot.reload" --history-api-fallback
>     npm ERR! You can get information on how to open an issue for this project with:
>     npm ERR!     npm bugs landscapes.io
>     npm ERR! Or if that isn't available, you can get their info via:
>     npm ERR!     npm owner ls landscapes.io
>     npm ERR! There is likely additional logging output above.
> 
>     npm ERR! Please include the following file with any support request:
>     npm ERR!     /home/ec2-user/landscapes.io/npm-debug.log
>     [ec2-user@ip-10-104-224-97 landscapes.io]$ less /home/ec2-user/landscapes.io/npm-debug.log

**Comment by matthewfincher** [comment]
MongoDB, NodeJS and NPM installed vis CloudFormation in UserData section. No manual installation required or desired.

**Comment by matthewfincher** [comment]
try `sudo npm install`

**Comment by zombyte** [comment]
Is this the appropriate cloud formation to use? If you can confirm and I will attempt the installation again and let you know how it goes. 

https://raw.githubusercontent.com/OpenWhere/landscapes.io/v2-develop/cloudFormation.json

The one used for the install can be see from the S3 bucket here: https://s3.us-east-2.amazonaws.com/landscapes-test/landscapes_cloudformation.json

I see the bash script at the end of the CloudFormation, but unsure if it was ran properly with the current install. Is there a log file for script output that can be reviewed to verify?

**Comment by zombyte** [comment]
Attempted installation again and the /var/log/cloud-init.log file mentions the below:

> Apr 20 13:25:18 localhost cloud-init: + sudo yum install -y gcc-c++ make
> Apr 20 13:25:18 localhost cloud-init: sudo: sorry, you must have a tty to run sudo

I then ran each of the commands in the bash script section of the cloud-init manually and switched to the wiki installation instructions starting at Installing Landscapes section. Attempting rpm install is producing the following output.

> [ec2-user@landscapes.io landscapes.io]$ npm install
> npm WARN deprecated @types/promises-a-plus@0.0.26: Use '--lib es6' to get Promise types.
> npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> Killed          ...] | extract:balanced-match: sill gunzTarPerm modified mode [ 'lib/ReactComponentTreeHookUMDShim.js', 420, 436 ]
> [ec2-user@landscapes.io landscapes.io]$ sudo su -
> Last login: Thu Apr 20 13:42:24 EDT 2017 on pts/0
> [root@landscapes.io ~]# cd /home/ec2-user/landscapes.io/
> [root@landscapes.io landscapes.io]# npm install
> npm WARN deprecated @types/promises-a-plus@0.0.26: Use '--lib es6' to get Promise types.
> npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> Killed         ....] / extract:setimmediate: sill gunzTarPerm extractEntry CHANGELOG.md
> [root@landscapes.io landscapes.io]# npm install
> npm WARN deprecated @types/promises-a-plus@0.0.26: Use '--lib es6' to get Promise types.
> npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> Killed          ...] / extract:mime: sill gunzTarPerm extractEntry lib/enums.js
> [root@landscapes.io landscapes.io]# npm install
> [    ..............] / fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/winston
> npm WARN deprecated @types/promises-a-plus@0.0.26: Use '--lib es6' to get Promise types.
> npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> Killed           ..] | extract:node-gyp: sill gunzTarPerm modified mode [ 'lib/jsdom/living/generated/CDATASection.js', 438, 420 ]
> [root@landscapes.io landscapes.io]# 
> [root@landscapes.io landscapes.io]# npm install
> npm WARN deprecated @types/promises-a-plus@0.0.26: Use '--lib es6' to get Promise types.
> npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> Killed           ..] - extract:escope: sill gunzTarPerm extractEntry core-js/math/pot.js

> [root@ip-10-104-224-186 landscapes.io]# npm install
> npm WARN deprecated @types/promises-a-plus@0.0.26: Use '--lib es6' to get Promise types.
> npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type definitions, so you don't need @types/redux installed!
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> Killed           ..] - extract:animate.css: sill gunzTarPerm extractEntry test/vectors/byte0168.dat
